### ISSUE TITLE
Chosen USB device controller is unavailable

### ISSUE THREAD

**Issue by yukifolf** [mphi-rc/pi-zero-security-key#4]
Hi I have a little problem with code:

Exception in thread "main" java.lang.IllegalStateException: Chosen USB device controller is unavailable
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at com.github.mphi_rc.usb.gadget.UsbDeviceController.check(UsbDeviceController.java:30)
        at com.github.mphi_rc.usb.gadget.ImmutableUsbDeviceController.validate(ImmutableUsbDeviceController.java:109)
        at com.github.mphi_rc.usb.gadget.ImmutableUsbDeviceController.of(ImmutableUsbDeviceController.java:105)
        at com.github.mphi_rc.usb.gadget.UsbDeviceController.raspberryPiZero(UsbDeviceController.java:17)
        at com.github.mphi_rc.fido2.Configuration.usbDeviceController(Configuration.java:49)
        at com.github.mphi_rc.fido2.ImmutableConfiguration.usbDeviceControllerInitialize(ImmutableConfiguration.java:266)
        at com.github.mphi_rc.fido2.ImmutableConfiguration.access$1600(ImmutableConfiguration.java:35)
        at com.github.mphi_rc.fido2.ImmutableConfiguration$InitShim.usbDeviceController(ImmutableConfiguration.java:203)
        at com.github.mphi_rc.fido2.ImmutableConfiguration.<init>(ImmutableConfiguration.java:73)
        at com.github.mphi_rc.fido2.ImmutableConfiguration.<init>(ImmutableConfiguration.java:35)
        at com.github.mphi_rc.fido2.ImmutableConfiguration$Builder.build(ImmutableConfiguration.java:868)
        at com.github.mphi_rc.fido2.ConfigurationFile.readFromDisk(ConfigurationFile.java:172)
        at com.github.mphi_rc.fido2.ConfigurationFile.<init>(ConfigurationFile.java:63)
        at com.github.mphi_rc.fido2.ConfigurationFile.defaultPath(ConfigurationFile.java:46)
        at com.github.mphi_rc.fido2.Fido2AuthenticatorCli.main(Fido2AuthenticatorCli.java:14)

And it can't run

**Comment by mphi-rc** [comment]
This error happens when your configuration points to an invalid or missing USB device controller.

If you are running this on a Pi Zero, make sure USB gadget support is enabled:
* your kernel must be compiled with configfs support (most Pi kernels are)
* kernel modules `libcomposite` and `dwc2` must be loaded
* `dtoverlay=dwc2` may need to be added to `/boot/config.txt`

If you are running this on a host without USB device controller hardware then you can use a software emulator. [This great article](https://www.collabora.com/news-and-blog/blog/2019/06/24/using-dummy-hcd/) explains how to do this using the dummy_hcd kernel module.

To verify whether you've set up your UDC correctly, look under `/sys/class/udc/`. The Pi Zero controller will appear as file `20980000.usb` and the emulated controller as `dummy_udc.0`.
